# Generated by Django 5.2.4 on 2026-04-11 21:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("receipt_url", models.URLField(blank=True, default="")),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="payments/receipts/"
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="customers.installment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin or customer who recorded this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="payments_pa_workspa_6e738e_idx",
                    ),
                    models.Index(
                        fields=["installment"], name="payments_pa_install_ca1c95_idx"
                    ),
                    models.Index(
                        fields=["transaction_reference"],
                        name="payments_pa_transac_2dc1cb_idx",
                    ),
                ],
            },
        ),
    ]
