# Generated by Django 5.2.4 on 2026-04-11 21:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="workspaces/logos/"
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=63)),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "support_whatsapp",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="core_worksp_slug_a852b9_idx"),
                    models.Index(
                        fields=["is_active"], name="core_worksp_is_acti_bc82e9_idx"
                    ),
                ],
            },
        ),
    ]
