# Generated by Django 5.2.4 on 2026-04-12 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_text", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        default="General",
                        help_text="e.g. Workspace, Billing, Customer, Property",
                        max_length=100,
                    ),
                ),
                ("link", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name_plural": "Workspace Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_reps_approve_bookings", models.BooleanField(default=False)),
                (
                    "can_reps_manage_subscriptions",
                    models.BooleanField(
                        default=False,
                        help_text="Requires can_reps_approve_bookings to be True",
                    ),
                ),
                ("can_reps_manage_sales_reps", models.BooleanField(default=False)),
                (
                    "notify_customer_on_booking_status",
                    models.BooleanField(default=True),
                ),
                ("notify_admin_on_new_booking", models.BooleanField(default=True)),
                (
                    "notify_customer_on_payment_receipt",
                    models.BooleanField(default=True),
                ),
            ],
            options={
                "verbose_name_plural": "Workspace Settings",
            },
        ),
        migrations.AddField(
            model_name="workspace",
            name="billing_plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("STARTER", "Starter"),
                    ("GROWTH", "Growth"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="create_estate_public_pages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="initial_payment_as_first_month",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workspace",
            name="instagram_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="workspace",
            name="intercom_app_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workspace",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="region",
            field=models.CharField(default="Nigeria", max_length=100),
        ),
        migrations.AddField(
            model_name="workspace",
            name="website_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="timezone",
            field=models.CharField(default="Africa/Lagos", max_length=63),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["billing_plan"], name="core_worksp_billing_d640c6_idx"
            ),
        ),
        migrations.AddField(
            model_name="workspaceactivity",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspaceactivity",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.workspace",
            ),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="core.workspace",
            ),
        ),
    ]
