# Generated by Django 5.2.4 on 2026-04-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workspaceinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="billing_plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("STARTER", "Starter"),
                    ("GROWTH", "Growth"),
                    ("SCALE", "Scale"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
    ]
