# Generated by Django 5.2.4 on 2026-04-13 21:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_scale_billing_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacesettings",
            name="commission_legend_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Default commission % for Legend tier sales reps.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="commission_senior_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Default commission % for Senior tier sales reps.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="commission_starter_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Default commission % for Starter tier sales reps.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
