# Generated by Django 5.2.4 on 2026-05-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_gallery_and_commission_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="facebook_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="workspace",
            name="linkedin_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="workspace",
            name="twitter_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="workspace",
            name="youtube_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
