# Generated by Django 5.2.4 on 2026-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_social_url_fields_to_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_booking_rejected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_commission_paid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_payment_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_payment_due_today",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_payment_overdue",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_payment_rejected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_payment_reminder_2d",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_payment_reminder_7d",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_plot_allocated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_property_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_realtor_added",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workspacesettings",
            name="notify_subscription_completed",
            field=models.BooleanField(default=True),
        ),
    ]
