# Generated by Django 5.2.4 on 2026-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_notification_toggle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="billing_pending_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspace",
            name="billing_pending_plan",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="workspace",
            name="billing_pending_receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="workspaces/receipts/"
            ),
        ),
        migrations.AlterField(
            model_name="workspaceinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                    ("CUSTOMER", "Customer"),
                    ("SALES_REP", "Sales Rep"),
                    ("CUSTOMER_REP", "Customer Rep"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
