# Generated by Django 5.2.4 on 2026-04-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_address_user_country_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otptoken",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, default="", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="otptoken",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="otptoken",
            index=models.Index(
                fields=["phone", "is_used"], name="accounts_ot_phone_aefce2_idx"
            ),
        ),
    ]
