# Generated by Django 5.2.4 on 2026-04-22 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="user",
            name="birth_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Birthday day (1–31)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Birthday month (1–12)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
