# Generated by Django 5.2.4 on 2026-04-11 21:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL_LAND", "Residential Land"),
                            ("FARM_LAND", "Farm Land"),
                            ("COMMERCIAL", "Commercial"),
                            ("MIXED_USE", "Mixed Use"),
                        ],
                        default="RESIDENTIAL_LAND",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "total_sqms",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("unit_measurement", models.CharField(default="sqm", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="properties/images/"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_name", models.CharField(max_length=255)),
                (
                    "land_size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Size allocated under this plan (in sqm)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("OUTRIGHT", "Outright"),
                            ("INSTALLMENT", "Installment"),
                        ],
                        default="INSTALLMENT",
                        max_length=20,
                    ),
                ),
                (
                    "initial_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Required initial/down payment",
                        max_digits=14,
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Total duration in months for installment plans",
                    ),
                ),
                (
                    "payment_spread_method",
                    models.CharField(
                        choices=[
                            ("INITIAL_SEPARATE", "Initial Separate"),
                            ("INITIAL_AS_FIRST", "Initial as First Month"),
                        ],
                        default="INITIAL_SEPARATE",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_installment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Computed monthly installment amount (auto-calculated)",
                        max_digits=14,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after a subscription uses this plan",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_plans",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bank_name", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="properties.property",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["workspace", "status"], name="properties__workspa_9f585a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type"], name="properties__propert_5c7790_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingplan",
            index=models.Index(
                fields=["workspace", "property"], name="properties__workspa_2cd193_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingplan",
            index=models.Index(
                fields=["is_active"], name="properties__is_acti_1c3bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["workspace", "property"], name="properties__workspa_d0168d_idx"
            ),
        ),
    ]
