# Generated by Django 5.2.4 on 2026-04-13 21:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_gallery_and_commission_overrides"),
        ("properties", "0002_add_amenity_document_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="commission_override_legend",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override workspace default Legend tier commission % for this property.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="commission_override_senior",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override workspace default Senior tier commission % for this property.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="commission_override_starter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override workspace default Starter tier commission % for this property.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.CreateModel(
            name="PropertyGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="properties/gallery/")),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order — lower numbers appear first.",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="properties.property",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "property"],
                        name="properties__workspa_6ffdfc_idx",
                    )
                ],
            },
        ),
    ]
