# Generated by Django 5.2.4 on 2026-04-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_add_gallery_and_commission_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="available_units",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of plots/units available for sale"
            ),
        ),
        migrations.AddField(
            model_name="propertylocation",
            name="nearest_landmark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
