# Generated by Django 5.2.4 on 2026-04-22 02:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_gallery_and_commission_overrides"),
        ("properties", "0004_add_available_units_and_nearest_landmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydocument",
            name="custom_document_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom name when document_type is OTHER.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_sqms",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Auto-computed from land inventory (land_size × total_slots for each LandSize).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LandSize",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "land_size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Plot size in SQM (e.g. 300, 500, 600)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "total_slots",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Total number of plots of this size available",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label e.g. 'Half Plot'",
                        max_length=255,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_sizes",
                        to="properties.property",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["land_size"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "property"],
                        name="properties__workspa_7b4dad_idx",
                    )
                ],
                "unique_together": {("property", "land_size")},
            },
        ),
    ]
