# Generated by Django 5.2.4 on 2026-04-24 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_gallery_and_commission_overrides"),
        ("properties", "0005_propertydocument_custom_document_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertydocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("PROVISIONAL_SURVEY", "Provisional Survey"),
                    ("REGISTERED_SURVEY", "Registered Survey"),
                    ("SURVEY_PLAN", "Survey Plan"),
                    ("C_OF_O", "Certificate of Occupancy (CofO)"),
                    ("ALLOCATION_LETTER", "Allocation Letter"),
                    ("CONTRACT_OF_SALES", "Contract of Sales"),
                    ("LAND_RECEIPT", "Land Receipt"),
                    ("DEED_OF_ASSIGNMENT", "Deed of Assignment"),
                    ("GOVERNORS_CONSENT", "Governor's Consent"),
                    ("EXCISION", "Excision"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="InspectionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting_point",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "virtual_link",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "available_days",
                    models.JSONField(
                        default=list, help_text='e.g. ["MON","WED","FRI"]'
                    ),
                ),
                ("time_from", models.TimeField(blank=True, null=True)),
                ("time_to", models.TimeField(blank=True, null=True)),
                ("max_persons", models.PositiveSmallIntegerField(default=5)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_config",
                        to="properties.property",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Configuration",
                "indexes": [
                    models.Index(
                        fields=["workspace", "property"],
                        name="properties__workspa_a7a359_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyAppreciation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_date", models.DateField()),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "percentage_change",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Auto-computed: ((new_price - old_price) / old_price) × 100",
                        max_digits=7,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appreciations",
                        to="properties.property",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "property"],
                        name="properties__workspa_63c3e9_idx",
                    ),
                    models.Index(
                        fields=["effective_date"], name="properties__effecti_4179cb_idx"
                    ),
                ],
            },
        ),
    ]
