# Generated by Django 5.2.4 on 2026-05-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_add_pricing_plan_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionconfig",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this inspection schedule is open for bookings",
            ),
        ),
        migrations.AddField(
            model_name="inspectionconfig",
            name="time_slots",
            field=models.JSONField(
                default=list,
                help_text="[{id, label, start_time, mode: RECURRING|ONE_TIME, date, is_active}]",
            ),
        ),
    ]
