# Generated by Django 5.2.4 on 2026-04-14 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_assigned_rep_subscription_assigned_rep"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPortalSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_sessions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token", "is_active"],
                        name="customers_c_token_c7a347_idx",
                    )
                ],
            },
        ),
    ]
