# Generated by Django 5.2.4 on 2026-04-16 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_gallery_and_commission_overrides"),
        ("customers", "0003_add_customer_portal_session"),
        ("properties", "0003_add_gallery_and_commission_overrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "property_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text fallback when no FK property is linked.",
                        max_length=255,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspection_time", models.TimeField(blank=True, null=True)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[("PHYSICAL", "Physical"), ("VIRTUAL", "Virtual")],
                        default="PHYSICAL",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "Residential"),
                            ("COMMERCIAL", "Commercial"),
                            ("FARM_LAND", "Farm Land"),
                        ],
                        default="RESIDENTIAL",
                        max_length=20,
                    ),
                ),
                ("persons", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ATTENDED", "Attended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "linked_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_inspections",
                        to="properties.property",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Inspection",
                "verbose_name_plural": "Site Inspections",
                "ordering": ["-inspection_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "inspection_date"],
                        name="customers_s_workspa_cfd542_idx",
                    ),
                    models.Index(
                        fields=["workspace", "status"],
                        name="customers_s_workspa_3b05ab_idx",
                    ),
                ],
            },
        ),
    ]
