# Generated by Django 5.2.4 on 2026-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_siteinspection_assigned_rep_converted_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="allocation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="allocation_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="allocation_letters/"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="allocation_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plot_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
