# Generated by Django 5.2.4 on 2026-04-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrep",
            name="tier",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter"),
                    ("SENIOR", "Senior"),
                    ("LEGEND", "Legend"),
                ],
                default="STARTER",
                max_length=20,
            ),
        ),
    ]
